#!/usr/bin/env node

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const source = join(packageRoot, "agents", "agent.md");
const filename = "wr-architect-agent.toml";
const owner = "# Generated by @windyroad/architect from agents/agent.md.";

function split(markdown) {
  const end = markdown.indexOf("\n---\n", 4);
  return markdown.startsWith("---\n") && end !== -1
    ? { frontmatter: markdown.slice(4, end), body: markdown.slice(end + 5) }
    : { frontmatter: "", body: markdown };
}

function description(frontmatter) {
  const lines = frontmatter.split(/\r?\n/);
  const start = lines.findIndex((line) => line.startsWith("description:"));
  if (start === -1) return "Architecture reviewer for structural and technology decisions.";
  const value = [lines[start].slice("description:".length).trim()];
  for (let index = start + 1; index < lines.length && /^\s+/.test(lines[index]); index += 1) {
    value.push(lines[index].trim());
  }
  return value.filter(Boolean).join(" ");
}

function payload() {
  const { frontmatter, body } = split(readFileSync(source, "utf8"));
  return [
    "# Do not edit by hand; update agents/agent.md and reinstall.",
    'name = "wr-architect:agent"',
    `description = ${JSON.stringify(description(frontmatter))}`,
    'sandbox_mode = "read-only"',
    'developer_instructions = """',
    body.replace(/\\/g, "\\\\").replace(/"""/g, '\\"\\"\\"').trimEnd(),
    '"""',
    "",
  ].join("\n");
}

export function renderArchitectAgent() {
  const content = payload();
  const hash = createHash("sha256").update(content).digest("hex");
  return `${owner}\n# Generated content SHA-256: ${hash}\n${content}`;
}

function owned(content) {
  if (!content.startsWith(`${owner}\n`)) return false;
  const lines = content.split("\n");
  const match = lines[1]?.match(/^# Generated content SHA-256: ([0-9a-f]{64})$/);
  return Boolean(match && createHash("sha256").update(lines.slice(2).join("\n")).digest("hex") === match[1]);
}

export function agentDir(scope, cwd = process.cwd(), env = process.env) {
  return scope === "user"
    ? join(env.CODEX_HOME || join(homedir(), ".codex"), "agents")
    : join(cwd, ".codex", "agents");
}

export function installArchitectAgent(targetDir, { quiet = false } = {}) {
  mkdirSync(targetDir, { recursive: true });
  const target = join(targetDir, filename);
  const expected = renderArchitectAgent();
  if (existsSync(target)) {
    const current = readFileSync(target, "utf8");
    if (current === expected) return false;
    if (!owned(current)) {
      if (!quiet) console.log(`Preserved user-managed Codex agent at ${target}.`);
      return false;
    }
  }
  writeFileSync(target, expected, "utf8");
  if (!quiet) console.log(`Codex architect agent installed at ${target}.`);
  return true;
}

export function uninstallArchitectAgent(targetDir) {
  const target = join(targetDir, filename);
  if (existsSync(target) && owned(readFileSync(target, "utf8"))) rmSync(target);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  if (process.argv.includes("--session-start") && !process.env.CODEX_THREAD_ID) process.exit(0);
  const scopeIndex = process.argv.indexOf("--scope");
  const scope = scopeIndex === -1 ? (process.argv.includes("--session-start") ? "user" : "project") : process.argv[scopeIndex + 1];
  const target = agentDir(scope);
  if (process.argv.includes("--uninstall")) uninstallArchitectAgent(target);
  else {
    const changed = installArchitectAgent(target, { quiet: process.argv.includes("--session-start") });
    if (changed && process.argv.includes("--session-start")) {
      console.log(JSON.stringify({ systemMessage: "wr-architect: Codex agent installed; restart Codex to activate it." }));
    }
  }
}
