#!/usr/bin/env bats

setup() {
  REPO_ROOT="$(cd "$(dirname "$BATS_TEST_FILENAME")/../../.." && pwd)"
  SYNC_SCRIPT="$REPO_ROOT/scripts/sync-codex-agents.mjs"
  ARCHITECT_AGENT_TOML="$REPO_ROOT/.codex/agents/wr-architect.toml"
  POLICY_AGENT_TOML="$REPO_ROOT/.codex/agents/wr-risk-scorer-policy.toml"
}

@test "sync-codex-agents: generated agent is in sync" {
  run node "$SYNC_SCRIPT" --check
  [ "$status" -eq 0 ]
  [[ "$output" == *"OK:"* ]]
}

@test "sync-codex-agents: generated agent points to Claude source of truth" {
  [ -f "$ARCHITECT_AGENT_TOML" ]
  run grep -n "Generated by scripts/sync-codex-agents.mjs" "$ARCHITECT_AGENT_TOML"
  [ "$status" -eq 0 ]
  run grep -n 'name = "wr-architect"' "$ARCHITECT_AGENT_TOML"
  [ "$status" -eq 0 ]
  run grep -n 'developer_instructions = """' "$ARCHITECT_AGENT_TOML"
  [ "$status" -eq 0 ]
  run grep -n "You are the Architect" "$ARCHITECT_AGENT_TOML"
  [ "$status" -eq 0 ]
}

@test "sync-codex-agents: generated risk policy agent points to Claude source of truth" {
  [ -f "$POLICY_AGENT_TOML" ]
  run grep -n "Generated by scripts/sync-codex-agents.mjs" "$POLICY_AGENT_TOML"
  [ "$status" -eq 0 ]
  run grep -n 'name = "wr-risk-scorer-policy"' "$POLICY_AGENT_TOML"
  [ "$status" -eq 0 ]
  run grep -n 'developer_instructions = """' "$POLICY_AGENT_TOML"
  [ "$status" -eq 0 ]
  run grep -n "You are the Risk Scorer in policy review mode" "$POLICY_AGENT_TOML"
  [ "$status" -eq 0 ]
  run grep -n "3-5 Low, 6-9 Medium" "$POLICY_AGENT_TOML"
  [ "$status" -eq 0 ]
}

@test "sync-codex-agents: npm scripts are wired" {
  run grep -n "sync:codex-agents" "$REPO_ROOT/package.json"
  [ "$status" -eq 0 ]
  run grep -n "check:codex-agents" "$REPO_ROOT/package.json"
  [ "$status" -eq 0 ]
}
