#!/usr/bin/env bats

setup() {
  REPO_ROOT="$(cd "$(dirname "$BATS_TEST_FILENAME")/../../.." && pwd)"
  SYNC_SCRIPT="$REPO_ROOT/scripts/sync-codex-agents.mjs"
  AGENT_TOML="$REPO_ROOT/.codex/agents/wr-architect.toml"
}

@test "sync-codex-agents: generated agent is in sync" {
  run node "$SYNC_SCRIPT" --check
  [ "$status" -eq 0 ]
  [[ "$output" == *"OK:"* ]]
}

@test "sync-codex-agents: generated agent points to Claude source of truth" {
  [ -f "$AGENT_TOML" ]
  run grep -n "Generated by scripts/sync-codex-agents.mjs" "$AGENT_TOML"
  [ "$status" -eq 0 ]
  run grep -n 'name = "wr-architect"' "$AGENT_TOML"
  [ "$status" -eq 0 ]
  run grep -n 'developer_instructions = """' "$AGENT_TOML"
  [ "$status" -eq 0 ]
  run grep -n "You are the Architect" "$AGENT_TOML"
  [ "$status" -eq 0 ]
}

@test "sync-codex-agents: npm scripts are wired" {
  run grep -n "sync:codex-agents" "$REPO_ROOT/package.json"
  [ "$status" -eq 0 ]
  run grep -n "check:codex-agents" "$REPO_ROOT/package.json"
  [ "$status" -eq 0 ]
}
