#!/usr/bin/env bats

setup() {
  REPO_ROOT="$(cd "$(dirname "$BATS_TEST_FILENAME")/../../.." && pwd)"
  SYNC_SCRIPT="$REPO_ROOT/scripts/sync-codex-agents.mjs"
  ARCHITECT_AGENT_TOML="$REPO_ROOT/.codex/agents/wr-architect.toml"
  RISK_AGENT_DIR="$REPO_ROOT/.codex/agents"
}

@test "sync-codex-agents: generated agent is in sync" {
  run node "$SYNC_SCRIPT" --check
  [ "$status" -eq 0 ]
  [[ "$output" == *"OK:"* ]]
}

@test "sync-codex-agents: generated agent points to Claude source of truth" {
  [ -f "$ARCHITECT_AGENT_TOML" ]
  run grep -n "Generated by scripts/sync-codex-agents.mjs" "$ARCHITECT_AGENT_TOML"
  [ "$status" -eq 0 ]
  run grep -n 'name = "wr-architect"' "$ARCHITECT_AGENT_TOML"
  [ "$status" -eq 0 ]
  run grep -n 'developer_instructions = """' "$ARCHITECT_AGENT_TOML"
  [ "$status" -eq 0 ]
  run grep -n "You are the Architect" "$ARCHITECT_AGENT_TOML"
  [ "$status" -eq 0 ]
}

@test "sync-codex-agents: all invoked risk agents use exact Codex identities" {
  for mode in pipeline plan wip policy external-comms inbound-report; do
    agent="$RISK_AGENT_DIR/wr-risk-scorer-${mode}.toml"
    [ -f "$agent" ]
    grep -q "^# Generated by @windyroad/risk-scorer from agents/${mode}.md" "$agent"
    grep -q "^name = \"wr-risk-scorer:${mode}\"$" "$agent"
    grep -q '^developer_instructions = """' "$agent"
  done

  grep -q "You are the Risk Scorer in policy review mode" "$RISK_AGENT_DIR/wr-risk-scorer-policy.toml"
  grep -q "3-5 Low, 6-9 Medium" "$RISK_AGENT_DIR/wr-risk-scorer-policy.toml"
  grep -q "EXTERNAL_COMMS_RISK_VERDICT" "$RISK_AGENT_DIR/wr-risk-scorer-external-comms.toml"
}

@test "sync-codex-agents: npm scripts are wired" {
  run grep -n "sync:codex-agents" "$REPO_ROOT/package.json"
  [ "$status" -eq 0 ]
  run grep -n "check:codex-agents" "$REPO_ROOT/package.json"
  [ "$status" -eq 0 ]
}
