#!/bin/bash
# P119: PreToolUse:Write enforcement hook for new problem ticket creation.
# New RFC documents are denied; fix proposals use release rows and stories.
#
# BLOCKS Write to:
#   - docs/problems/<NNN>-*.<status>.md      (when file does not yet exist
#                                             and Step-2 grep marker absent)
#   - docs/rfcs/RFC-<NNN>-*.<status>.md      (when file does not yet exist)
#
# Marker convention:
#   - /tmp/manage-problem-grep-${SESSION_ID}        (problems tier;
#                                                    set by manage-problem /
#                                                    capture-problem Step 2)
#
# Out of scope (allow-listed):
#   - docs/problems/README.md  — regenerated by manage-problem Steps 5/6/7
#   - docs/rfcs/README.md      — regenerated by manage-rfc transitions / review
#   - Existing files           — Edit-flow / status transitions are
#                                governed by /wr-itil:transition-problem and
#                                /wr-itil:manage-rfc respectively
#   - Edit tool                — only Write is gated; Edit on existing
#                                tickets is normal status-transition shape
#   - Non-ticket basenames     — only ticket-shaped paths are gated:
#                                problems: NNN-*.md  (3-digit prefix)
#                                rfcs:     RFC-NNN-*.md
#                                Other docs (NOTES.md, archive/, etc.)
#                                are project housekeeping, not tickets
#
# ADR-031 forward-compat: matcher uses path-prefix + ticket-shape basename,
# agnostic to current suffix-based layout vs. future per-state subdirectory
# layout. The RFC branch redirects to the release-row capture flow.
#
# References:
#   ADR-009  — gate marker lifecycle (per-session /tmp markers).
#   ADR-013 Rule 1 — deny redirects to the relevant skill (manage-problem
#                    for problems; capture-rfc for RFCs) where Step 2 fires.
#   ADR-022  — problem lifecycle (status suffixes covered: open / known-error /
#              verifying / parked).
#   ADR-038  — progressive disclosure (deny message stays terse + actionable).
#   ADR-060  — Problem-RFC-Story framework.
#   P119     — agent bypasses Step 2 by writing tickets directly.
#   P170     — driver problem ticket for the RFC framework introduction.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=lib/create-gate.sh
source "$SCRIPT_DIR/lib/create-gate.sh"

INPUT=$(cat)

TOOL_NAME=$(echo "$INPUT" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    print(data.get('tool_name', ''))
except:
    print('')
" 2>/dev/null || echo "")

FILE_PATH=$(echo "$INPUT" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    print(data.get('tool_input', {}).get('file_path', ''))
except:
    print('')
" 2>/dev/null || echo "")

SESSION_ID=$(echo "$INPUT" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    print(data.get('session_id', ''))
except:
    print('')
" 2>/dev/null || echo "")

# Only gate the Write tool. Edit on existing tickets is the
# transition-problem surface, not the new-ticket surface.
if [ "$TOOL_NAME" != "Write" ]; then
  exit 0
fi

# Empty file_path or session_id — fail-open (mirror jtbd-enforce-edit.sh).
# Empty session_id with a real file_path could be a hook harness call;
# do not deny on parse-incomplete input.
if [ -z "$FILE_PATH" ]; then
  exit 0
fi

if [ -z "$SESSION_ID" ]; then
  exit 0
fi

# Match docs/problems/ OR docs/rfcs/ paths only. Both absolute
# (project-root prefixed) and relative shapes are accepted because
# Claude Code passes absolute paths in tool_input.file_path but tests
# and direct invocations may use relative paths.
TIER=""
case "$FILE_PATH" in
  *docs/problems/*) TIER="problems" ;;
  *docs/rfcs/*)     TIER="rfcs" ;;
  *) exit 0 ;;
esac

BASENAME=$(basename "$FILE_PATH")

# Allow-list: README.md regenerated by skill flows (chicken-and-egg).
# Applies to both tiers: docs/problems/README.md (manage-problem Steps 5/6/7)
# and docs/rfcs/README.md (manage-rfc transitions / review).
if [ "$BASENAME" = "README.md" ]; then
  exit 0
fi

# Only gate ticket-shaped basenames per tier:
#   problems: NNN-... (3-digit prefix)
#   rfcs:     RFC-NNN-...
# Non-ticket files (NOTES.md, archive/index.md, etc.) are project
# housekeeping and don't need the gate.
case "$TIER" in
  problems)
    case "$BASENAME" in
      [0-9][0-9][0-9]-*) ;;
      *) exit 0 ;;
    esac
    ;;
  rfcs)
    case "$BASENAME" in
      RFC-[0-9][0-9][0-9]-*) ;;
      *) exit 0 ;;
    esac
    ;;
esac

# Existing file — Edit-flow / status-transition path. Only block
# new-file creation (the Write that materialises a brand-new ticket).
if [ -f "$FILE_PATH" ]; then
  exit 0
fi

# P142 / ADR-050: the runtime-SID instrumentation hook
# (itil-runtime-sid-marker.sh) writes the runtime stdin session_id to a
# per-machine marker on every PreToolUse:Bash|Write|Edit|Read event. The
# `get_current_session_id` helper reads that marker as the authoritative
# SID, so the marker `mark_step2_complete`
# writes is bound to the same session_id this hook will see on the
# subsequent Write. SID-mismatch denial is structurally eliminated; the
# only remaining deny path is the routine "duplicate-check / capture
# step has not run yet for this session" case.

# New ticket Write: gate on the tier-specific marker.
case "$TIER" in
  problems)
    if check_create_gate "$SESSION_ID"; then
      exit 0
    fi
    create_gate_deny "BLOCKED: Cannot Write '${BASENAME}' under docs/problems/ without running /wr-itil:manage-problem Step 2 (duplicate-check) first. New problem tickets MUST be created via the skill so the duplicate-prevention grep fires before the file lands. Invoke the Skill tool with skill='wr-itil:manage-problem' and a description of the new problem; Step 2 will grep for related existing tickets and surface any matches via AskUserQuestion before creating the new ticket. (P119)"
    exit 0
    ;;
  rfcs)
    create_gate_deny "BLOCKED: New RFC documents are retired. Use /wr-itil:capture-rfc to draw a problem-traced release row with at least one story on an existing story map. Existing RFC documents remain editable for legacy lifecycle transitions."
    exit 0
    ;;
esac
exit 0
