#!/usr/bin/env node

import {
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ownerMarker = "# Generated by @windyroad/risk-scorer from ";

const externalCommsCodexInstructions = `

## Codex completion marker compatibility

Codex encrypts custom-agent spawn prompts before PostToolUse hooks receive them.
When the request contains a \`SURFACE:\` line and a \`<draft>...</draft>\` block,
compute the canonical marker key with the same normalization documented above:

1. For \`changeset-author\`, remove leading YAML frontmatter and its following blank line.
2. Convert CRLF and CR line endings to LF.
3. Remove trailing whitespace from every line, then from the complete draft.
4. Compute lowercase SHA-256 over \`normalized draft + "\\n" + surface\`.

Use a local shell or Python command to compute the digest; do not estimate it.
On PASS, append \`EXTERNAL_COMMS_RISK_KEY: <64 lowercase hex characters>\` after
the verdict. On FAIL, do not emit a key. This is generated Codex-only behavior;
the completion hook independently validates the key shape before writing a marker.`;

const pipelineCodexInstructions = `

## Codex assessed-checkout binding

You are the endpoint pipeline scorer. Score the supplied state directly. Do
not invoke the \`wr-risk-scorer:pipeline\` skill and do not spawn or delegate to
another pipeline scorer; that wrapper exists for callers, not for this agent.

The request must contain exactly one \`RISK_CWD: <absolute Git root>\` line.
Repeat that exact line once after the structured risk output so the completion
bridge can bind marker generation to the checkout that was assessed. Do not
repeat the path elsewhere. If the request omits the line or provides more than
one, do not emit \`RISK_SCORES\`; report that the assessed checkout is unbound.

The returned \`RISK_CWD\` is also the caller's command root. Subsequent governed
commands must put \`cd <RISK_CWD> &&\` inside the command itself; a Codex tool
\`workdir\` alone may be hidden from checkout-binding hooks.`;

export const riskAgentSpecs = [
  ["pipeline", "Scores pipeline actions for cumulative residual risk."],
  ["plan", "Reviews implementation plans and projected release risk."],
  ["wip", "Assesses cumulative work-in-progress pipeline risk."],
  ["policy", "Validates RISK-POLICY.md drafts for ISO 31000 compliance."],
  ["external-comms", "Reviews outbound prose for confidentiality and credibility risk."],
  ["inbound-report", "Reviews inbound reports for request and fix risk."],
].map(([mode, fallbackDescription]) => ({
  mode,
  name: `wr-risk-scorer:${mode}`,
  filename: `wr-risk-scorer-${mode}.toml`,
  source: join(packageRoot, "agents", `${mode}.md`),
  sourceLabel: `agents/${mode}.md`,
  fallbackDescription,
}));

function splitFrontmatter(markdown) {
  if (!markdown.startsWith("---\n")) return { frontmatter: "", body: markdown };
  const end = markdown.indexOf("\n---\n", 4);
  if (end === -1) return { frontmatter: "", body: markdown };
  return {
    frontmatter: markdown.slice(4, end),
    body: markdown.slice(end + 5),
  };
}

function frontmatterValue(frontmatter, key) {
  const line = frontmatter.split(/\r?\n/).find((item) => item.startsWith(`${key}:`));
  return line ? line.slice(key.length + 1).trim() : "";
}

function tomlMultiline(value) {
  return value.replace(/\\/g, "\\\\").replace(/"""/g, '\\"\\"\\"').trimEnd();
}

function renderPayload(spec) {
  const { frontmatter, body } = splitFrontmatter(readFileSync(spec.source, "utf8"));
  const description = frontmatterValue(frontmatter, "description") || spec.fallbackDescription;
  const instructions = spec.mode === "external-comms"
    ? `${body.trimEnd()}${externalCommsCodexInstructions}`
    : spec.mode === "pipeline"
      ? `${body.trimEnd()}${pipelineCodexInstructions}`
      : body;
  return [
    "# Do not edit by hand; update the Claude agent markdown and regenerate.",
    `name = ${JSON.stringify(spec.name)}`,
    `description = ${JSON.stringify(description)}`,
    'sandbox_mode = "read-only"',
    'developer_instructions = """',
    tomlMultiline(instructions),
    '"""',
    "",
  ].join("\n");
}

function payloadHash(payload) {
  return createHash("sha256").update(payload).digest("hex");
}

export function renderRiskAgent(spec) {
  const payload = renderPayload(spec);
  return [
    `${ownerMarker}${spec.sourceLabel}.`,
    `# Generated content SHA-256: ${payloadHash(payload)}`,
    payload,
  ].join("\n");
}

function isUnmodifiedGenerated(content, spec) {
  if (!content.startsWith(`${ownerMarker}${spec.sourceLabel}.\n`)) return false;
  const lines = content.split("\n");
  const hashMatch = lines[1]?.match(/^# Generated content SHA-256: ([0-9a-f]{64})$/);
  if (hashMatch) return payloadHash(lines.slice(2).join("\n")) === hashMatch[1];

  // Migrate the marker-only format generated by the unreleased pilot.
  return content === [`${ownerMarker}${spec.sourceLabel}.`, renderPayload(spec)].join("\n");
}

export function installRiskAgents(targetDir, { quiet = false } = {}) {
  mkdirSync(targetDir, { recursive: true });
  let changed = 0;
  let preserved = 0;
  for (const spec of riskAgentSpecs) {
    const target = join(targetDir, spec.filename);
    const expected = renderRiskAgent(spec);
    if (!existsSync(target)) {
      writeFileSync(target, expected, "utf8");
      changed += 1;
      continue;
    }
    const current = readFileSync(target, "utf8");
    if (current === expected) continue;
    if (isUnmodifiedGenerated(current, spec)) {
      writeFileSync(target, expected, "utf8");
      changed += 1;
    } else {
      preserved += 1;
    }
  }
  if (!quiet) console.log(`Codex risk agents: ${changed} updated, ${riskAgentSpecs.length - changed - preserved} current, ${preserved} preserved.`);
  return changed;
}

export function checkRiskAgents(targetDir) {
  return riskAgentSpecs.every((spec) => {
    const target = join(targetDir, spec.filename);
    return existsSync(target) && readFileSync(target, "utf8") === renderRiskAgent(spec);
  });
}

export function uninstallRiskAgents(targetDir, { quiet = false } = {}) {
  let removed = 0;
  for (const spec of riskAgentSpecs) {
    const target = join(targetDir, spec.filename);
    if (!existsSync(target)) continue;
    if (!isUnmodifiedGenerated(readFileSync(target, "utf8"), spec)) continue;
    rmSync(target);
    removed += 1;
  }
  if (!quiet) console.log(`Codex risk agents: ${removed} removed.`);
  return removed;
}

export function agentDirForScope(scope, cwd = process.cwd(), env = process.env) {
  if (scope === "user") {
    return join(env.CODEX_HOME || join(homedir(), ".codex"), "agents");
  }
  return join(cwd, ".codex", "agents");
}

function argValue(name) {
  const index = process.argv.indexOf(name);
  return index >= 0 ? process.argv[index + 1] : "";
}

async function main() {
  const sessionStart = process.argv.includes("--session-start");
  if (sessionStart && !process.env.CODEX_THREAD_ID) return;

  let sessionStartInput = {};
  if (sessionStart) {
    let input = "";
    process.stdin.setEncoding("utf8");
    for await (const chunk of process.stdin) input += chunk;
    try {
      sessionStartInput = JSON.parse(input);
    } catch {
      sessionStartInput = {};
    }
  }

  const targetArg = argValue("--target");
  const scope = argValue("--scope") || (sessionStart ? "user" : "project");
  const targetDir = targetArg || agentDirForScope(scope);
  const quiet = sessionStart || process.argv.includes("--quiet");

  if (process.argv.includes("--check")) {
    if (!checkRiskAgents(targetDir)) process.exitCode = 1;
    return;
  }
  if (process.argv.includes("--uninstall")) {
    uninstallRiskAgents(targetDir, { quiet });
    return;
  }

  const changed = installRiskAgents(targetDir, { quiet });
  if (sessionStart && changed > 0) {
    const message = "wr-risk-scorer: Codex agents installed; restart Codex to activate them.";
    console.log(JSON.stringify({ systemMessage: message }));
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await main();
}
