#!/usr/bin/env node

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const source = join(root, "agents", "hang-off-check.md");
const filename = "wr-itil-hang-off-check.toml";
const owner = "# Generated by @windyroad/itil from agents/hang-off-check.md.";
const sourceId = /\b(?:ADR-\d{3,}|P-?\d{3}|RFC-\d{3,}|JTBD-\d{3,}|STORY(?:-MAP)?-\d{3,}|R-?\d{3})\b/g;

function split(markdown) {
  const end = markdown.indexOf("\n---\n", 4);
  return markdown.startsWith("---\n") && end !== -1
    ? { frontmatter: markdown.slice(4, end), body: markdown.slice(end + 5) }
    : { frontmatter: "", body: markdown };
}

function description(frontmatter) {
  const lines = frontmatter.split(/\r?\n/);
  const start = lines.findIndex((line) => line.startsWith("description:"));
  if (start === -1) return "Decide whether a problem belongs under an existing ticket.";
  const value = [lines[start].slice("description:".length).trim()];
  for (let index = start + 1; index < lines.length && /^\s+/.test(lines[index]); index += 1) value.push(lines[index].trim());
  return value.filter(Boolean).join(" ").replace(sourceId, "a source governance record");
}

function instructions(body) {
  return body
    .replaceAll("AskUserQuestion", "request_user_input")
    .replaceAll("Agent tool", "native Codex subagent tool")
    .replaceAll("packages/itil/", "the installed ITIL plugin/")
    .replace(sourceId, "the referenced source governance record");
}

function payload() {
  const { frontmatter, body } = split(readFileSync(source, "utf8"));
  return [
    "# Do not edit by hand; update agents/hang-off-check.md and reinstall.",
    'name = "wr-itil:hang-off-check"',
    `description = ${JSON.stringify(description(frontmatter))}`,
    'sandbox_mode = "read-only"',
    'developer_instructions = """',
    instructions(body).replace(/\\/g, "\\\\").replace(/"""/g, '\\"\\"\\"').trimEnd(),
    '"""',
    "",
  ].join("\n");
}

export function renderAgent() {
  const content = payload();
  const hash = createHash("sha256").update(content).digest("hex");
  return `${owner}\n# Generated content SHA-256: ${hash}\n${content}`;
}

function owned(content) {
  if (!content.startsWith(`${owner}\n`)) return false;
  const lines = content.split("\n");
  const match = lines[1]?.match(/^# Generated content SHA-256: ([0-9a-f]{64})$/);
  return Boolean(match && createHash("sha256").update(lines.slice(2).join("\n")).digest("hex") === match[1]);
}

export function agentDir(scope, cwd = process.cwd(), env = process.env) {
  return scope === "user" ? join(env.CODEX_HOME || join(homedir(), ".codex"), "agents") : join(cwd, ".codex", "agents");
}

export function installAgent(targetDir, { quiet = false } = {}) {
  mkdirSync(targetDir, { recursive: true });
  const target = join(targetDir, filename);
  const expected = renderAgent();
  if (existsSync(target)) {
    const current = readFileSync(target, "utf8");
    if (current === expected) return false;
    if (!owned(current)) {
      if (!quiet) console.log(`Preserved user-managed Codex agent at ${target}.`);
      return false;
    }
  }
  writeFileSync(target, expected, "utf8");
  if (!quiet) console.log(`Codex ITIL agent installed at ${target}.`);
  return true;
}

export function uninstallAgent(targetDir) {
  const target = join(targetDir, filename);
  if (existsSync(target) && owned(readFileSync(target, "utf8"))) rmSync(target);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  if (process.argv.includes("--session-start") && !process.env.CODEX_THREAD_ID) process.exit(0);
  const scopeIndex = process.argv.indexOf("--scope");
  const scope = scopeIndex === -1 ? (process.argv.includes("--session-start") ? "user" : "project") : process.argv[scopeIndex + 1];
  const target = agentDir(scope);
  if (process.argv.includes("--uninstall")) uninstallAgent(target);
  else {
    const changed = installAgent(target, { quiet: process.argv.includes("--session-start") });
    if (changed && process.argv.includes("--session-start")) {
      console.log(JSON.stringify({ systemMessage: "wr-itil: Codex hang-off-check agent installed; restart Codex to activate it." }));
    }
  }
}
